react-brasil/conf

public/index.html, src/App.js, src/components/Header.js, src/utils/Globals.js
This is the start of a serie of PRs to introduce a better approach on code as well as a few changes on the layout itself.
=> Clean up header

src/components/Header.js
para resolver o problema da issue #17
=> replace vw at header component to %

package.json, yarn.lock
=> Improvements

package.json, public/favicon.ico/manifest.json, public/index.html, src/index.js, src/registerServiceWorker.js, yarn.lock
https://github.com/facebookincubator/create-react-app/releases/tag/v1.0.7
=> Migrating 1.0.7

README.md
I put the members of the core team according to the amount of contribution of the repo.
What do you guys think?
=> Add core team

src/components/BuyTickets.js
Ajuste label botão de comprar ingresso
=> Change button buy tickets label

src/components/C4P.js, src/components/Meetup.js, src/components/Sponsor.js, src/components/Topics.js, src/utils/Globals.js
- remove midia kit link
- add sponsors
- add contrast colors
- remove extra topics
- add meetup rj
=> feature/midia kit, sponsor, colors, meetups, topics

src/components/C4P.js, src/components/Item.js, src/components/Ticket.js, src/components/Title.js, src/utils/Globals.js
=> Improve contrast - Fix #54

src/components/Header.js
=> Added vh to fit the total height of the window size.

src/components/Header.js
=> Revert "Added vh to fit the total height of the window size."

src/components/Header.js, src/components/Speakers.js, src/components/Sponsor.js, src/components/Supporters.js
=> Post 1.0.0 RC > MASTER

src/components/Sponsor.js, src/components/Supporters.js
now you can track your links leads from react conf br landing page
=> Added campaign tracking in logo's sponsors links.

package.json, src/App.js
=> fix overflow x hidden body html, insert release package.json

src/components/BuyIngressos.js, src/components/Ingresso.js
=> disable buy tickets button

LICENSE, package.json, public/index.html, src/components/AfterParty.js, src/components/BuyIngressos.js, src/components/Contact.js, src/components/Event.js, src/components/Footer.js, src/components/Ingresso.js, src/components/Speakers.js, src/components/Title.js, src/components/Venue.js
Release Candidate to Master
#79 #77
=> POST 1.0.4-RC 👉 Master

src/components/Speakers.js, src/components/Sponsor.js
=> [Fix] Update pipefy link

package.json, src/components/Speakers.js, src/components/Sponsor.js
=> Post 1.0.6 RC 👉 MASTER

src/components/Venue.js
=> [Feature] Add medium link

package.json, src/components/Venue.js
=> Post 1.0.7 RC 👉 Master

src/components/C4P.js, src/utils/Globals.js
=> Encerrado C4P #119
